Allow jumping to godot quickfix errors (#75)
* Create a compiler script for quickfix

When you use :GodotRun, you get output in your quickfix. Some of it has
useful error messages. With this compiler, you can jump directly to
those errors.

Godot outputs filenames including res:// and we match those directly
which works because of godot#edit_res_path from PR #60 (2a35d6b).

Example output that it can parse:

SCRIPT ERROR: Parse Error: Expected end of statement after expression, found "Identifier" instead.
   at: GDScript::reload (res://light/hotspot_light.gd:12)
   GDScript backtrace (most recent call first):
       [0] save_children_states (res://room/room_data.gd:128)
       [1] store_states (res://i_room.gd:341)
ERROR: Failed to load script "res://mainmenu/scene_transition.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not preload resource script "res://shared/input/device_icons.gd".
          at: GDScript::reload (res://mainmenu/eggplant.gd:6)
ERROR: Failed to instantiate an autoload, script 'res://mainmenu/eggplant.gd' does not inherit from 'Node'.
   at: (main/main.cpp:3207)
SCRIPT ERROR: Invalid call to function 'get_world_cellv' in base 'TileMap (gridworld.gd)'. Expected 2 arguments.
          at: _process (res://games/drop_walker/code/player.gd:73)

Parsed into:

res://light/hotspot_light.gd|12 error| Parse Error: Expected end of statement after expression, found "Identifier" instead.
||    GDScript backtrace (most recent call first):
res://room/room_data.gd|128| save_children_states
res://i_room.gd|341| store_states
res://mainmenu/scene_transition.gd|| Parse error
res://mainmenu/eggplant.gd|6 error| Parse Error: Could not preload resource script "res://shared/input/device_icons.gd".
res://mainmenu/eggplant.gd|| does not inherit from 'Node'.
res://games/drop_walker/code/player.gd|73 error| Invalid call to function 'get_world_cellv' in base 'TileMap (gridworld.gd)'. Expected 2 arguments.

There's a mix of support for Godot 4.1 and 4.5 in here because it seems
they changed logging to prefix with "ERROR: " and added GDScript
backtraces.

* Parse the simple error format from the Output pane

If you load a project with compile errors, you'll see them in the Output
pane like this:

  res://main.gd:8 - Parse Error: Unexpected "Identifier" in class body.
  res://containers/card_list.gd:2 - Parse Error: Could not resolve super class inheritance from "AbstractContainer".

You can copy those, paste them in a vim buffer, and load them:
    :compiler godot | cgetbuffer

On Godot 4.5, these Output window errors have a prefixed "ERROR:":
  ERROR: res://joke.gd:13 - Parse Error: Expected end of statement after return statement, found "," instead.

I'm not certain what version of Godot this changed, but seems like we
should handle both for now so "ERROR:" isn't used as part of the
filename.

Test
* Click the Output pane's copy button in Godot and load in vim.